### ISSUE TITLE
Eclipse MDSL Editor install broken

### ISSUE THREAD

**Issue by ejuntu** [Microservice-API-Patterns/MDSL-Specification#37]
Hi, I was trying to install the Eclipse MDSL Editor, but installation failed with following error:
> Cannot complete the install because one or more required items could not be found.
> Software being installed: MDSL Editor Feature Developer Resources 5.4.6.202202011408 (io.mdsl.feature.source.feature.group 5.4.6.202202011408)
> Missing requirement: io.mdsl 5.4.6.202202011408 (io.mdsl 5.4.6.202202011408) requires 'osgi.bundle; org.slf4j.api 0.0.0' but it could not be found
>  Cannot satisfy dependency:
>    From: MDSL Editor Feature 5.4.6.202202011408 (io.mdsl.feature.feature.group 5.4.6.202202011408)
>    To: org.eclipse.equinox.p2.iu; io.mdsl [5.4.6.202202011408,5.4.6.202202011408]
>  Cannot satisfy dependency:
>    From: MDSL Editor Feature Developer Resources 5.4.6.202202011408 (io.mdsl.feature.source.feature.group 5.4.6.202202011408)
>    To: org.eclipse.equinox.p2.iu; io.mdsl.feature.feature.group [5.4.6.202202011408,5.4.6.202202011408]

Any chance this can be remedied? Would really like to use the MDSL tools.

**Comment by socadk** [comment]
Hi @ejuntu which Eclipse version did you use? You might want to try an older one. I succeeded with this one (not installed but .zip unpacked):  

* Version: 2023-03 (4.27.0)
* Build id: 20230309-1520
 
Not an ideal solution, but very limited dev. resources for maintenance here... a CLI is available, as well as a Web prototype, supporting parts of the functionality (all generators are there): https://github.com/Microservice-API-Patterns/MDSL-Web

Hope this helps

**Comment by socadk** [comment]
Should be fixed with MDSL Version 6, developed for Eclipse 06-2024
